/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myfirstjni_NativeClass */

#ifndef _Included_com_example_myfirstjni_NativeClass
#define _Included_com_example_myfirstjni_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myfirstjni_NativeClass
 * Method:    HelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myfirstjni_NativeClass_HelloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
